[package]
name = "rstrapwire-module"
version = "0.1.0"
edition = "2021"

[lib]
name = "rstrapwire"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
c_str_macro = "1.0.2"
rsmgp-sys = { path = "../rsmgp-sys" }
